<a href="https://colab.research.google.com/github/Tianlong1089/PythonDataScience/blob/SKT_CheatSheets_InterestingCodes/DataFrames_HealtVaccineCorrel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np

In [3]:
# the proportion of children in the dataset who had a mother with the education levels equal to less than high school (<12), high school (12), more than high school but not a college graduate (>12) and college degree.

In [4]:
df=pd.read_csv('NISPUF17.csv')


In [ ]:
#Ejemplo por resolver
'''
{"less than high school":0.2,
    "high school":0.4,
    "more than high school but not college":0.2,
    "college":0.2} 
'''

In [ ]:
df['EDUC1'].head()

0    4
1    3
2    3
3    4
4    1
Name: EDUC1, dtype: int64

In [ ]:
df['EDUC1'].unique()

array([4, 3, 1, 2])

In [ ]:
df[df['EDUC1'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, SEQNUMC, SEQNUMHH, PDAT, PROVWT_D, RDDWT_D, STRATUM, YEAR, AGECPOXR, HAD_CPOX, AGEGRP, BF_ENDR06, BF_EXCLR06, BF_FORMR08, BFENDFL06, BFFORMFL06, C1R, C5R, CBF_01, CEN_REG, CHILDNM, CWIC_01, CWIC_02, EDUC1, FRSTBRN, I_HISP_K, INCPORAR, INCPORAR_I, INCPOV1, INCQ298A, LANGUAGE, M_AGEGRP2, MARITAL2, MOBIL_I, NUM_PHONE, NUM_CELLS_HH, NUM_CELLS_PARENTS, RACE_K, RACEETHK, RENT_OWN, SEX, ESTIAP17, EST_GRANT, STATE, D6R, D7, N_PRVR, PROV_FAC, REGISTRY, VFC_ORDER, HEP_BRTH, HEP_FLAG, P_NUHEPX, P_NUHIBX, P_NUHPHB, P_NUMDAH, P_NUMDHI, P_NUMDIH, P_NUMDTA, P_NUMDTP, P_NUMFLU, P_NUMFLUL, P_NUMFLUM, P_NUMFLUN, P_NUMHEA, P_NUMHEN, P_NUMHEP, P_NUMHG, P_NUMHHY, P_NUMHIB, P_NUMHIN, P_NUMHION, P_NUMHM, P_NUMHS, P_NUMIPV, P_NUMMCN, P_NUMMMR, P_NUMMMRX, P_NUMMMX, P_NUMMP, P_NUMMPR, P_NUMMRV, P_NUMMS, P_NUMMSM, P_NUMMSR, P_NUMOLN, P_NUMOPV, P_NUMPCV, P_NUMPCP, P_NUMPCC, P_NUMPCC7, P_NUMPCC13, P_NUMPCCN, P_NUMPCN, P_NUMPOL, P_NUMRB, P_NUMRG, P_NUMRM, P_NUMRO, P_NUMROT, ...]
Index: []

[0 rows x 454 columns]

In [ ]:
print(df['EDUC1'].value_counts()[1])

2904


In [ ]:
full_size=len(df['EDUC1'])
list_selec=[df['EDUC1'].value_counts()[i]/full_size for i in range(1,5)]
list_keys=["less than high school","high school","more than high school but not college","college"]
res_dct = {list_keys[i]:list_selec[i] for i in range(0, len(list_keys))}
res_dct

{'less than high school': 0.10202002459160373,
 'high school': 0.172352011241876,
 'more than high school but not college': 0.24588090637625154,
 'college': 0.47974705779026877}

In [ ]:
#  Return a tuple of the average number of influenza vaccines for those children we know received breastmilk as a child and those who know did not.

In [50]:
df['CBF_01'].unique()  # tomaron leche  Yes No

array([ 1,  2, 99, 77])

In [54]:
#df['P_NUMFLU'].fillna(method="ffill").unique()
df['P_NUMFLU']=df['P_NUMFLU'].fillna(df['P_NUMFLU'].mean())

In [91]:
df['P_NUMFLU'].where(df['CBF_01']==1).dropna().mean()

1.862525874180097

In [92]:
df['P_NUMFLU'].where(df['CBF_01']==2).dropna().mean()

1.7216533710500808

In [ ]:
#Calculate the ratio of the number of children who contracted chickenpox but were vaccinated against it (at least one varicella dose) versus those who were vaccinated but did not contract chicken pox. 

In [ ]:
'''
{"male":0.2,
    "female":0.4}
'''

In [93]:
df['SEX'] # Male Female

0        1
1        1
2        2
3        2
4        2
        ..
28460    2
28461    2
28462    2
28463    2
28464    2
Name: SEX, Length: 28465, dtype: int64

In [95]:
df['HAD_CPOX'].unique() #Yes No Don’t know Refused Missing


array([ 2,  1, 77, 99])

In [7]:
df['P_NUMVRC']=df['P_NUMVRC'].fillna(0.0)

In [8]:
df['P_NUMVRC'].unique()

array([0., 1., 2., 3.])

In [31]:
Pos_Vac_Men=df['SEX'].where((df['P_NUMVRC']>0) & (df['HAD_CPOX'] ==1) & (df['SEX']== 1)).dropna().value_counts()
Pos_Novac_Men=df['SEX'].where((df['P_NUMVRC']>0) & (df['HAD_CPOX'] ==2) & (df['SEX']== 1)).dropna().value_counts()
ratioaMen=Pos_Vac_Men/Pos_Novac_Men
ratioaMen.iloc[0]

0.009675583380762664

1.0    150
Name: SEX, dtype: int64

In [30]:
Pos_Vac_Wom=df['SEX'].where((df['P_NUMVRC']>0) & (df['HAD_CPOX'] ==1) & (df['SEX']== 2)).dropna().value_counts()
Pos_Novac_Wom=df['SEX'].where((df['P_NUMVRC']>0) & (df['HAD_CPOX'] ==2) & (df['SEX']== 2)).dropna().value_counts()
ratioWomen= Pos_Vac_Wom/Pos_Novac_Wom 
ratioWomen.iloc[0]

0.0077918259335489565

In [32]:
{"male":ratioaMen.iloc[0],    "female":ratioWomen.iloc[0]}

{'male': 0.009675583380762664, 'female': 0.0077918259335489565}

In [ ]:
### Correlacion entre vacunas e decremento de enfermedades.

In [33]:
def corr_chickenpox():
    import scipy.stats as stats
    import numpy as np
    import pandas as pd
    df=pd.read_csv('NISPUF17.csv')
    df['P_NUMVRC']=df['P_NUMVRC'].fillna(0.0)
    # this is just an example dataframe
    #df=pd.DataFrame({"had_chickenpox_column":np.random.randint(1,3,size=(100)),"num_chickenpox_vaccine_column":np.random.randint(0,6,size=(100))})
    corr, pval=stats.pearsonr(df['HAD_CPOX'],df['P_NUMVRC']) 
    
    return corr

    # YOUR CODE HERE
    #raise NotImplementedError()

In [34]:
assert -1<=corr_chickenpox()<=1